site_name: razikus.tech
site_author: Adam Raźniewski
site_description: >-
  Personal blog about various technological stuff. 
copyright: Copyright &copy; 2023 Adam Raźniewski
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - offline
  - search
  - social
  - tags:
      tags_file: blog/index.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.svg
  custom_dir: overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Razikus
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/razniewski/
  generator: false
  consent:
    actions:
      - accept
    title: Cookie consent
    description: >- 
      I'm using cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my website and gather some Google Analytics.
    analytics:
      name: Google Analytics
      checked: true
  analytics:
    provider: google
    property: !ENV [GOOGLE_TAG, 'nope']
    feedback:
      title: Was this article cool?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This article was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This article could be improved
          data: 0
          note: >- 
            Thanks for your feedback!


  homepage: https://razikus.tech
nav:
  - index.md
  - Blog:
    - blog/index.md
    - "2023":
      - blog/novela.ink.md
  - Contact:
    - contact/index.md